# Generated by Django 3.2.9 on 2021-12-16 13:51

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30, null=True, unique=True)),
                ('group_description', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('user_name', models.CharField(max_length=30, null=True, verbose_name='First name')),
                ('user_surname', models.CharField(max_length=30, null=True, verbose_name='Last name')),
                ('nickname', models.CharField(max_length=30, null=True, unique=True)),
                ('user_staff', models.BooleanField(default=False, null=True)),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.groupofusers')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=64, null=True, verbose_name="Task's title")),
                ('task_text', models.TextField(null=True, verbose_name="Task's text")),
                ('task_performer', multiselectfield.db.fields.MultiSelectField(choices=[('id=1', 'Messi'), ('id=2', 'Ronaldo'), ('id=3', 'Lewandowski'), ('id=4', 'Haaland'), ('id=5', 'Chiesa'), ('id=6', 'Benzema')], max_length=6)),
                ('task_limit_days', models.DurationField(blank=True, help_text='Max duration of days for this task', null=True)),
                ('task_create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('task_update_date', models.DateTimeField(auto_now=True, null=True)),
                ('task_image', models.ImageField(null=True, upload_to='tasks/%Y/%m/%d/')),
                ('task_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.taskuser', verbose_name="Task's author")),
            ],
        ),
    ]
