# Generated by Django 3.2.9 on 2021-12-16 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskuser',
            name='group',
        ),
        migrations.RemoveField(
            model_name='taskuser',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Task's author"),
        ),
        migrations.DeleteModel(
            name='GroupOfUsers',
        ),
        migrations.DeleteModel(
            name='TaskUser',
        ),
    ]
