# Generated by Django 3.2.9 on 2021-12-17 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_auto_20211217_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersTasksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='task_limit_days',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='task_performer',
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Task's author"),
        ),
        migrations.DeleteModel(
            name='UserTaskModel',
        ),
        migrations.AddField(
            model_name='userstasksmodel',
            name='tasks_performers',
            field=models.ManyToManyField(blank=True, to='tasks.TaskModel'),
        ),
        migrations.AddField(
            model_name='userstasksmodel',
            name='users_performers',
            field=models.ManyToManyField(blank=True, help_text="Choice for task's performers", to=settings.AUTH_USER_MODEL),
        ),
    ]
