# Generated by Django 3.2.9 on 2021-12-17 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0007_auto_20211217_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstasksmodel',
            name='users_performers',
            field=models.ManyToManyField(blank=True, help_text="Choice for task's performers", related_name='user_set', related_query_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
