# Generated by Django 3.2.9 on 2021-12-17 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0008_alter_userstasksmodel_users_performers'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='tasks_performers',
            field=models.ManyToManyField(blank=True, related_name='group_set', related_query_name='group', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='users_performers',
            field=models.ManyToManyField(blank=True, help_text="Choice for task's performers", related_name='user_set', related_query_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UsersTasksModel',
        ),
    ]
